var app=getApp();
Page({
	onLoad:function(){
		app.editPage();
		var _this=this;
		wx.getStorage({
			key:"userInfo",
			success:function(res){
				wx.switchTab({
					url:"/pages/index/index"
				})
			},fail:function(){
				setTimeout(function(){
					_this.setData({
						code:app.globalData.code,
						openid:app.globalData.openid
					});
				},1000)
				_this.setData({
					disabled:true,
					reason:false
				});
			}
		})
	},
	inputName:function(e){
		this.setData({
			name:e.detail.value
		})
		this.checkForm();
	},
	inputPass:function(e){
		this.setData({
			password:e.detail.value
		})
		this.checkForm();
	},
	checkForm:function(){
		
		if(this.data.name && this.data.name!="" && this.data.password && this.data.password!=""){
			this.setData({
				disabled:false
			})
		}else{
			this.setData({
				disabled:true
			})
		}
	},
	formSubmit:function(e){
		console.log(e)
		var _this=this;
		app.util.find("/index.php?r=site/login",e.detail.value).then(function(res){
			console.log("login",res)
			if(res.status==1){
				wx.setStorage({
					key:"userInfo",
					data:res.data,
					success:function(){
						wx.switchTab({
							url:"/pages/index/index"
						})
					}
				});
			}else if(res.status==0){
				_this.setData({
					reason:true
				});
			}
		})
	}
})